### ISSUE TITLE
Fails to renew certificates due to mgmt locks

### ISSUE THREAD

**Issue by Flasheh** [shibayan/keyvault-acmebot#195]
**Describe the bug**
This is somewhat related to #193 but I was looking for a different solution.

I have an acmebot deployed for a while now and it worked fine. But recently I implemented management locks for resources we can't instantly recover from via Terraform/IaC. DNS zones being one of them.

So the bot is now failing to renew my certificates because it cannot delete the TXT records:

"Message":"The scope '/subscriptions/---/resourceGroups/---/providers/Microsoft.Network/dnsZones/---/TXT/_acme-challenge' cannot perform delete operation because following scope(s) are locked: '/subscriptions/---/resourceGroups/---/providers/Microsoft.Network/dnszones/---'. Please remove the lock and try again."

Should this not just update the record instead of deletion and recreation? I would really prefer to keep this resource locked.

Other than this, the project has been great so far, thanks!

**To Reproduce**
1. Deploy keyvault-acmebot and issue a certificate
2. Setup a management lock on the DNS zone resource
3. Watch it fail to renew

**Environment (please complete the following information):**
 - Certificate Type: Wildcards
 - Certificate Deploy Target: Key Vault

**Comment by shibayan** [comment]
I don't intend to change this behavior because the ACME specification recommends deleting it and because some DNS Providers cannot be updated.

Ref: https://github.com/shibayan/keyvault-acmebot/issues/152#issuecomment-688232296

It must be resolved with RBAC or Terraform Lifecycle instead of resource locks.

**Comment by Flasheh** [comment]
For future reference, in addition to RBAC and TF lifecycles, you cal also scope your management locks to one or more records within your DNS zone. This way your zone is still protected but acmebot can do it's thing.

**Comment by sopelt** [comment]
Also for future reference: [This article](https://docs.microsoft.com/en-us/azure/dns/dns-protect-zones-recordsets#protecting-individual-records) explains how to secure single/central DNS records (instead of the whole resource group or dns zone) which helps against accidental deletion of a zone while keeping keyvault-acmebot happy!
