### ISSUE TITLE
Allow RBAC/IAM instead of key vault policies

### ISSUE THREAD

**Issue by sopelt** [shibayan/keyvault-acmebot#213]
keyvault-acmebot could optionally support RBAC on keyvault (in preview for some time, see https://docs.microsoft.com/en-us/azure/key-vault/general/rbac-guide ) to allow more fine-grained access than key vault access policies currently provide. This would enable having a single keyvault-acmebot deployment with different consumers only having access to their respective certificate.

A scenario where this would come in handy: Multiple hostnames/certificates that are to be used by different appliances each having a principle only authorized on one certificate/secret.
Right now one would either have to live with the fact that an appliance can fetch certificates of other devices or deploy multiple keyvault-acmebot instances and live with that organizational overhead.

This should mainly be a deployment/ARM issue, as the template might have to be conditional as the policy and rbac modes are mutually exclusive.

Thank you for all your work!

**Comment by shibayan** [comment]
I would like to support RBAC in Key Vault at the time of GA.

It should still work by manually switching to RBAC, but since many documents assume Access Policy, I can imagine that it will cause confusion for users. In particular, the documentation for using certificates in App Service / CDN / Front Door has not been updated for RBAC.

I will support RBAC when these issues are resolved.

**Comment by sopelt** [comment]
Thanks for the swift reply. It looks like GA is still 6 months+ away for this feature according to https://github.com/MicrosoftDocs/azure-docs/issues/68143#issuecomment-754111648
