### ISSUE TITLE
Certificate policy subject is empty after renewal

### ISSUE THREAD

**Issue by Extant-1** [shibayan/keyvault-acmebot#216]
**Describe the bug**
After Acmebot renews a certificate that was added to the key vault, the policy subject is empty which causes issue with terraform since it is expected data.

**To Reproduce**
1. Add a certificate to key vault
2. Edit certificate to add the Issued and Endpoint tags so acmebot will renew it.
3. Manually start acmebot renewcertificate azure function
4. Certificate will get renewed with the policy subject empty

![image](https://user-images.githubusercontent.com/28478122/104689382-8a0f6200-5756-11eb-988d-67aee0387731.png)

**Environment (please complete the following information):**
 - Certificate Type: Sub-Domain
 - Certificate Deploy Target: App Gateway

**Comment by shibayan** [comment]
This is an issue with the Terraform Provider and has already been fixed in v2.22.0.
https://github.com/terraform-providers/terraform-provider-azurerm/blob/v2.22.0/CHANGELOG.md

Key Vault does not require you to specify a subject, and the issued certificate will automatically be assigned a subject, so there is no problem.

**Comment by Extant-1** [comment]
Looks like it was fixed for terraform data source but the issue still exists for the resource. I've created a bug with azurerm: https://github.com/terraform-providers/terraform-provider-azurerm/issues/10197
