### ISSUE TITLE
Excessive network transfer issue

### ISSUE THREAD

**Issue by shibayan** [shibayan/keyvault-acmebot#276]
Monthly transfer volume has exceeded 300GB and is likely to increase in the future, so consider countermeasures.

- Introduced CDN (Cloudflare)
- Stop automatic updates and require manual updates
- Sponsorship

**Comment by GeorgDangl** [comment]
Another idea might also be to reach out to Microsoft. Your project brings incredible value to those that use it in Azure, and that might be a good case for getting credits.
I don't have any contacts there directly, but aren't you an MVP for Azure? I'm sure there's someone you could talk to and ask😀

For the Cloudflare point, we would need to check what file types ate being transferred, since not everything is cached by their free tier. But they also might be able to help out a community project that focuses on making SSL for everyone more accessible.

**Comment by shibayan** [comment]
I examined the access log to Storage, I found that there were an unusually large number of accesses from a specific IP address.

![image](https://user-images.githubusercontent.com/1356444/109669066-1796fc00-7bb5-11eb-961c-601d0ccdb408.png)

However, this IP address is not a public one, which makes it very puzzling.
