### ISSUE TITLE
Add domain to existing cert

### ISSUE THREAD

**Issue by bbakermmc** [shibayan/keyvault-acmebot#45]
I know we can make a wildcard cert, but it would be nice if there was a way to load an existing cert with all its domains, add/remove domains and have it use the same cert name.

**Comment by shyamal890** [comment]
Yes, looking for something similar. I was thinking instead of mentioning all the sub-domains in the step below. 

![image](https://user-images.githubusercontent.com/6606965/65381975-d80a8600-dd19-11e9-902f-6169c517870e.png)

We can mention `*.somedomain.com` and the keyvault-function would automatically detect all the sub-domains added till now and certificates to all the domains.
