### ISSUE TITLE
Does this support running periodically with a timer trigger? 

### ISSUE THREAD

**Issue by stuartleeks** [shibayan/keyvault-acmebot#60]
I am currently using https://github.com/ohadschn/letsencrypt-webapp-renewer for a number of Azure Web Apps, but now want to also generate certs for Azure CDN. It looks like I can use `keyvault-acmebot` for both, but I want to be able to set it up to run every month to renew the certs automatically. Is that possible?

**Comment by shibayan** [comment]
The Key Vault Certificate created by this function is automatically renewed by the timer 30 days before it expires.

Since the CDN / Front Door / Application Gateway does not recognize the renewal of the Key Vault Certificate, you will need to provide a function to renew the certificate using the Key Vault Event Grid.

I heard from the CDN / Front Door team that automatic update will be supported around Q1 2020, so there is no plan to support this function.

**Comment by prajith234** [comment]
I am facing issue with Adding new certificate , If i open the https://xx-xxx.azurewebsites.net/add-certificate link its throwing me 401 error , But i can access https://xx-xxx.azurewebsites.net function app, Do you have any idea what is the cause ?

Thanks
Prajith

**Comment by sopelt** [comment]
Hello @shibayan, do you have a reference on App Gateway not recognizing renewal/rotation?

I was under the impression that this should work according to https://docs.microsoft.com/en-us/azure/application-gateway/key-vault-certs

> The instances also poll Key Vault at 24-hour intervals to retrieve a renewed version of the certificate, if it exists. If an updated certificate is found, the SSL certificate currently associated with the HTTPS listener is automatically rotated.

I didn't find similar statements for CDN/front door ... so it might be the case for them.

Thanks!

**Comment by shibayan** [comment]
It seems that my perception was wrong about App Gateway. The documentation states that it will be updated automatically.
