### ISSUE TITLE
Questions about pricing

### ISSUE THREAD

**Issue by Marcel0024** [shibayan/keyvault-acmebot#64]
So i'm still a bit new to azure. Sorry if this is a dumb question.

- When creating the template it also creates a application insights resource, why is this needed?

- So when request a certificate via _domain/add-certificate_ it auto renews every 60 days? Thats what the function does?

- Key Vault pricing on azure states 3 euro for renewals. Does that mean for this app as wel? so a certificate wil be renewed 6 times a year so that's 18 eu a year?

Thanks!

**Comment by shibayan** [comment]
>When creating the template it also creates a application insights resource, why is this needed?

It is created because it is necessary for monitoring the operation of Azure Functions. Up to 5GB free.

>So when request a certificate via domain/add-certificate it auto renews every 60 days? Thats what the function does?

Certificate renewal occurs approximately 30 days before expiration. Function saves the updated certificate to Key Vault.

>Key Vault pricing on azure states 3 euro for renewals. Does that mean for this app as wel? so a certificate wil be renewed 6 times a year so that's 18 eu a year?

The renewal price of Key Vault should be the price when using the associated CA. I checked my statement and it was less than $1 a year.

**Comment by Marcel0024** [comment]
Alright thanks!

**Comment by Marcel0024** [comment]
@shibayan New updates - like your last commit. Do i need to do anything on my side?

**Comment by shibayan** [comment]
You do not need to do anything.  Everything is automatically updated.
