### ISSUE TITLE
Certificate renewed, but Azure ContainerApp still says "certificate soon expires" and I need to update binding (manually)

### ISSUE THREAD

**Issue by fritzfs** [shibayan/keyvault-acmebot#758]
**Is your feature request related to a problem? Please describe.**
I am using a custom domain on Azure ContainerApp (ACA) with the combination of Azure Key Vault and Let's Encrypt. Now with keyvault-acmebot I can renew a certificate, but ACA still says the certificate will soon expire and I probably need to click manually update binding. 

**Describe the solution you'd like**
How can I trigger binding update with keyvault-acmebot? If I can.

![Screenshot 2024-09-06 at 14 38 14](https://github.com/user-attachments/assets/46454eab-7388-41f0-a25e-08a8bd2ce363)

![Screenshot 2024-09-06 at 14 45 03](https://github.com/user-attachments/assets/01618ccc-8980-41be-ba16-6ceddf0df591)

**Comment by shibayan** [comment]
Since it is the Container App that is responsible for renewing the certificate imported from Key Vault, it is thought that it will be rotated within 12 hours, as per the following document.

>Rotate certificates
When you rotate your certificate in Key Vault, Azure Container Apps automatically updates the certificate in your environment. It takes up to 12 hours for the new certificate to be applied.

- https://learn.microsoft.com/en-us/azure/container-apps/key-vault-certificates-manage#rotate-certificates

If it is not rotated automatically, it is likely a problem with Container Apps, so we recommend checking with Azure support.

**Comment by BarryBahrami** [comment]
Is this a letsencrypt certificate?  They only last 90 days.  in my
experience, Azure by default displays these certs as expiring soon.

Thank you,

Barry Bahrami

**Comment by fritzfs** [comment]
@shibayan you were right, it seems that Azure updated it after 4 hours. I missed that part of the documentation (https://learn.microsoft.com/en-us/azure/container-apps/key-vault-certificates-manage#rotate-certificates).
